module.exports = [ 
  { title: 'G1 - Dólar opera em queda em dia de baixo volume de negócios ...',
    link: 'http://g1.globo.com/economia/mercados/noticia/2015/12/dolar-cotacao-de-23-12-15.html',
    description: '12 horas atrás ... Após abrir esta quarta-feira (23) em alta, perto dos R$ 4, o dólar passou a cair \nem relação ao real e manteve a trajetória de baixa ao longo do ...',
    href: 'http://g1.globo.com/economia/mercados/noticia/2015/12/dolar-cotacao-de-23-12-15.html' },
  { title: 'G1 - Dólar fecha em queda nesta terça após superar R$ 4 na ...',
    link: 'http://g1.globo.com/economia/mercados/noticia/2015/12/dolar-fecha-em-queda-nesta-terca-apos-superar-r-4-na-vespera.html',
    description: '1 dia atrás ... O dólar fechou em queda frente a real nesta terça-feira (22), depois de superar a \nmarca de R$ 4 na véspera pela primeira vez desde outubro, ...',
    href: 'http://g1.globo.com/economia/mercados/noticia/2015/12/dolar-fecha-em-queda-nesta-terca-apos-superar-r-4-na-vespera.html' },
  { title: 'Moedas | Valor Econômico',
    link: 'http://www.valor.com.br/valor-data/moedas',
    description: 'USD Dólar Comercial. Dólar Comercial ... Dólar Turismo, 3,8700, 4,1300, -0,84%\n, 23/12 - 16:24 ... Euro x Dólar - Bacen, 1,0906, 1,0907, -0,57%, 23/12 - 13:11.',
    href: 'http://www.valor.com.br/valor-data/moedas' },
  { title: 'Converter Dólar EUA - Real Brasileiro - Advfn',
    link: 'http://br.advfn.com/conversor-moedas/dolar-eua-para-real-brasileiro.html',
    description: 'Converter Dólar EUA - Real Brasileiro Conversão e calculadora de moedas \ninternacionais de mais de 150 paises do mundo em tempo-real e spot.',
    href: 'http://br.advfn.com/conversor-moedas/dolar-eua-para-real-brasileiro.html' },
  { title: 'Histórico e Cotações do Dólar | FinanceOne',
    link: 'http://financeone.com.br/moedas/cotacoes-do-dolar/',
    description: 'Verifique a cotação do dólar hoje, assim como suas variações de cotações dolar \nreal, dolar libra, dolar euro em gráficos demonstrativos e consultas definidas.',
    href: 'http://financeone.com.br/moedas/cotacoes-do-dolar/' },
  { title: 'Dólar Hoje - valor do dolar hoje',
    link: 'http://dolarhoje.com/',
    description: 'Dólar Hoje. Valor da cotação do dólar americano hoje. Preço do dólar sempre \natualizado.',
    href: 'http://dolarhoje.com/' },
  { title: 'Índice Dólar - Dollar Index - Investing.com',
    link: 'http://br.investing.com/quotes/us-dollar-index',
    description: 'Aqui você encontra um panorama do índice dólar (USDX) informações e dados \nhistóricos, um gráfico avançado em tempo real e um relatório técnico.',
    href: 'http://br.investing.com/quotes/us-dollar-index' },
  { title: 'Câmbio | Cotações de Moedas, Taxas de Câmbio e mais | InfoMoney',
    link: 'http://www.infomoney.com.br/mercados/cambio',
    description: 'O dólar recuou 0,85 por cento, a 3,9885 reais na venda, após subir quase 2 por \ncento na véspera e terminar acima de 4 reais pela primeira vez em mais de dois\n ...',
    href: 'http://www.infomoney.com.br/mercados/cambio' },
  { title: 'O que (ainda) vale a pena comprar no exterior com o dólar mais caro?',
    link: 'http://economia.terra.com.br/o-que-ainda-vale-a-pena-comprar-no-exterior-com-o-dolar-mais-caro,93914b576170428a864ff0b5b8c861e6tzcgt0ww.html',
    description: '1 dia atrás ... Nos últimos anos, os Estados Unidos – com preços atrativos e dólar valendo \nmenos de R$ 2 - sempre foram o paraíso das compras para os ...',
    href: 'http://economia.terra.com.br/o-que-ainda-vale-a-pena-comprar-no-exterior-com-o-dolar-mais-caro,93914b576170428a864ff0b5b8c861e6tzcgt0ww.html' },
  { title: 'Dólar Turismo – Cotação de Hoje | dolarhoje.com.br',
    link: 'http://www.dolarhoje.com.br/dolar-turismo/',
    description: 'O dólar turismo representa a cotação da moeda americana para viagens de \nbrasileiros aos EUA ou outros lugares onde a aceita e vice versa. O valor difere \ndo ...',
    href: 'http://www.dolarhoje.com.br/dolar-turismo/' },
  { title: 'Dólar Hoje - Valor da Cotação - Preço Comercial | dolarhoje.com.br',
    link: 'http://www.dolarhoje.com.br/',
    description: 'Saiba o valor da cotação do dólar hoje em tempo real! Veja qual a história do \npreço do dólar comercial nos últimos dias.',
    href: 'http://www.dolarhoje.com.br/' },
  { title: 'Valor do Dolar | Cotação do Dolar Hoje',
    link: 'http://www.conversor-dolar.com.br/',
    description: 'O dólar (Código ISO: USD) é a moeda oficial dos Estados Unidos e a mais \nutilizada em transações internacionais. O preço do dólar no Brasil é determinado\n ...',
    href: 'http://www.conversor-dolar.com.br/' },
  { title: 'Dólar | Tópicos | EXAME.com',
    link: 'http://exame.abril.com.br/topicos/dolar',
    description: 'Confira últimas notícias, opiniões, resenhas, fotos e vídeos sobre Dólar em \nEXAME.com.',
    href: 'http://exame.abril.com.br/topicos/dolar' },
  { title: 'Dólar Americano - USD - SP Mundi Câmbio',
    link: 'https://www.spmundi.com.br/dolar',
    description: 'O dólar dos Estados Unidos é a moeda emitida pelos Estados Unidos e utilizada \nno mundo inteiro, tanto em reservas internacionais como em livre circulação ...',
    href: 'https://www.spmundi.com.br/dolar' },
  { title: 'Dólar dos Estados Unidos – Wikipédia, a enciclopédia livre',
    link: 'https://pt.wikipedia.org/wiki/D%C3%B3lar_dos_Estados_Unidos',
    description: 'O dólar dos Estados Unidos (em inglês: United States dollar) é a moeda emitida \npelos Estados Unidos e utilizada no mundo inteiro, tanto em reservas ...',
    href: 'https://pt.wikipedia.org/wiki/D%C3%B3lar_dos_Estados_Unidos' },
  { title: 'Artigos Empiricus - Dólar - Empiricus Research',
    link: 'http://www.empiricus.com.br/ad/Outbrain8.html',
    description: 'A relação de preço entre o dólar e o real depende de aspectos estruturais e \nmacroeconômicos. O momento de Brasil, Estados Unidos e o mundo no geral \ndeve ...',
    href: 'http://www.empiricus.com.br/ad/Outbrain8.html' },
  { title: 'Bee Câmbio: Comprar Dólar, Euro, Peso, Libra',
    link: 'http://www.beecambio.com.br/',
    description: 'Primeira casa de Câmbio Online. Segurança e transparência nas taxas. Compre \nonline e receba em casa. Atendimento especializado é aqui.',
    href: 'http://www.beecambio.com.br/' },
  { title: 'Como driblar a alta do dólar - Cadastro - Estadão',
    link: 'http://cadastro.estadao.com.br/comum/includes/estadao/head_header.php?area=topicos&t=Como%20driblar%20a%20alta%20do%20d%26oacute%3Blar&d=Saiba%20tudo%20sobre%20D%C3%B3lar%2C%20veja%20not%C3%ADcias%2C%20fotos%20e%20v%C3%ADdeos%20reunidos%20no%20canal%20de%20T%C3%B3picos%20do%20Estad%C3%A3o.&k=d%C3%B3lar%2Cnot%C3%ADcias%2Cv%C3%ADdeos%2Cfotos&s=estadao2014/topicos/teste',
    description: 'Saiba tudo sobre Dólar, veja notícias, fotos e vídeos reunidos no canal de \nTópicos do Estadão.',
    href: 'http://cadastro.estadao.com.br/comum/includes/estadao/head_header.php?area=topicos&t=Como%20driblar%20a%20alta%20do%20d%26oacute%3Blar&d=Saiba%20tudo%20sobre%20D%C3%B3lar%2C%20veja%20not%C3%ADcias%2C%20fotos%20e%20v%C3%ADdeos%20reunidos%20no%20canal%20de%20T%C3%B3picos%20do%20Estad%C3%A3o.&k=d%C3%B3lar%2Cnot%C3%ADcias%2Cv%C3%ADdeos%2Cfotos&s=estadao2014/topicos/teste' },
  { title: 'Notícias sobre dólar - Economia: Notícias e Opiniões - Zero Hora',
    link: 'http://zh.clicrbs.com.br/rs/noticias/economia/ultimas-noticias/tag/dolar/',
    description: 'Mercado financeiro 18/12/2015 | 17h58. Bolsa cai para menor patamar desde \n2009 com troca na Fazenda. Ibovespa caiu quase 3% nesta sexta-feira, e o dólar\n ...',
    href: 'http://zh.clicrbs.com.br/rs/noticias/economia/ultimas-noticias/tag/dolar/' },
  { title: 'Cotação do dia do dólar, euro e índices - Ágora Corretora',
    link: 'https://www.agorainvest.com.br/cotacoes/%5C%5C%5C',
    description: 'Ágora Corretora - Consulte as cotações: dólar, euro, Indice Bovespa (IBOV), Dow \nJones, Nasdaq e outros. Clique aqui e saiba mais!',
    href: 'https://www.agorainvest.com.br/cotacoes/%5C%5C%5C' } ]
